export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: { Row: { id: string; display_name: string | null; avatar_url: string | null; role: Database['public']['Enums']['app_role']; created_at: string; updated_at: string }; Insert: { id: string; display_name?: string | null; avatar_url?: string | null; role?: Database['public']['Enums']['app_role']; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['profiles']['Insert']>; Relationships: [] };
      coach_client_relationships: { Row: { id: number; trainer_id: string; client_id: string; status: Database['public']['Enums']['relationship_status']; created_at: string; updated_at: string }; Insert: { id?: never; trainer_id: string; client_id: string; status?: Database['public']['Enums']['relationship_status']; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['coach_client_relationships']['Insert']>; Relationships: [] };
      exercises: { Row: { id: number; name: string; description: string | null; primary_muscles: string[]; secondary_muscles: string[]; equipment: string[]; movement_pattern: string | null; difficulty: string | null; is_active: boolean; created_at: string; updated_at: string }; Insert: { id?: never; name: string; description?: string | null; primary_muscles?: string[]; secondary_muscles?: string[]; equipment?: string[]; movement_pattern?: string | null; difficulty?: string | null; is_active?: boolean; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['exercises']['Insert']>; Relationships: [] };
      exercise_variations: { Row: { id: number; exercise_id: number; name: string; notes: string | null; created_at: string }; Insert: { id?: never; exercise_id: number; name: string; notes?: string | null; created_at?: string }; Update: Partial<Database['public']['Tables']['exercise_variations']['Insert']>; Relationships: [] };
      programs: { Row: { id: number; trainer_id: string; client_id: string | null; name: string; description: string | null; status: Database['public']['Enums']['program_status']; start_date: string | null; end_date: string | null; created_at: string; updated_at: string }; Insert: { id?: never; trainer_id: string; client_id?: string | null; name: string; description?: string | null; status?: Database['public']['Enums']['program_status']; start_date?: string | null; end_date?: string | null; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['programs']['Insert']>; Relationships: [] };
      program_days: { Row: { id: number; program_id: number; day_index: number; name: string; notes: string | null }; Insert: { id?: never; program_id: number; day_index: number; name: string; notes?: string | null }; Update: Partial<Database['public']['Tables']['program_days']['Insert']>; Relationships: [] };
      program_exercises: { Row: { id: number; program_day_id: number; exercise_id: number; variation_id: number | null; order_index: number; target_sets: number | null; target_reps_min: number | null; target_reps_max: number | null; target_weight: number | null; target_rir: number | null; target_rest_seconds: number | null; notes: string | null }; Insert: { id?: never; program_day_id: number; exercise_id: number; variation_id?: number | null; order_index: number; target_sets?: number | null; target_reps_min?: number | null; target_reps_max?: number | null; target_weight?: number | null; target_rir?: number | null; target_rest_seconds?: number | null; notes?: string | null }; Update: Partial<Database['public']['Tables']['program_exercises']['Insert']>; Relationships: [] };
      workouts: { Row: { id: number; client_id: string; trainer_id: string | null; program_day_id: number | null; status: Database['public']['Enums']['workout_status']; scheduled_for: string | null; started_at: string | null; completed_at: string | null; notes: string | null; created_at: string; updated_at: string }; Insert: { id?: never; client_id: string; trainer_id?: string | null; program_day_id?: number | null; status?: Database['public']['Enums']['workout_status']; scheduled_for?: string | null; started_at?: string | null; completed_at?: string | null; notes?: string | null; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['workouts']['Insert']>; Relationships: [] };
      workout_exercises: { Row: { id: number; workout_id: number; exercise_id: number; variation_id: number | null; order_index: number; notes: string | null; created_at: string }; Insert: { id?: never; workout_id: number; exercise_id: number; variation_id?: number | null; order_index: number; notes?: string | null; created_at?: string }; Update: Partial<Database['public']['Tables']['workout_exercises']['Insert']>; Relationships: [] };
      workout_sets: { Row: { id: number; workout_exercise_id: number; set_index: number; set_type: Database['public']['Enums']['set_type']; weight: number | null; reps: number | null; duration_seconds: number | null; rir: number | null; rpe: number | null; is_completed: boolean; notes: string | null; created_at: string }; Insert: { id?: never; workout_exercise_id: number; set_index: number; set_type?: Database['public']['Enums']['set_type']; weight?: number | null; reps?: number | null; duration_seconds?: number | null; rir?: number | null; rpe?: number | null; is_completed?: boolean; notes?: string | null; created_at?: string }; Update: Partial<Database['public']['Tables']['workout_sets']['Insert']>; Relationships: [] };
      bodyweight_logs: { Row: { id: number; client_id: string; weight: number; unit: string; recorded_on: string; notes: string | null; created_at: string }; Insert: { id?: never; client_id: string; weight: number; unit?: string; recorded_on: string; notes?: string | null; created_at?: string }; Update: Partial<Database['public']['Tables']['bodyweight_logs']['Insert']>; Relationships: [] };
      body_measurements: { Row: { id: number; client_id: string; chest: number | null; waist: number | null; hips: number | null; arms: number | null; thighs: number | null; unit: string; recorded_on: string; notes: string | null; created_at: string }; Insert: { id?: never; client_id: string; chest?: number | null; waist?: number | null; hips?: number | null; arms?: number | null; thighs?: number | null; unit?: string; recorded_on: string; notes?: string | null; created_at?: string }; Update: Partial<Database['public']['Tables']['body_measurements']['Insert']>; Relationships: [] };
      nutrition_profiles: { Row: { user_id: string; calorie_target: number | null; protein_target_g: number | null; carbs_target_g: number | null; fat_target_g: number | null; dietary_preference: string | null; allergies: string[]; goals: string | null; updated_at: string }; Insert: { user_id: string; calorie_target?: number | null; protein_target_g?: number | null; carbs_target_g?: number | null; fat_target_g?: number | null; dietary_preference?: string | null; allergies?: string[]; goals?: string | null; updated_at?: string }; Update: Partial<Database['public']['Tables']['nutrition_profiles']['Insert']>; Relationships: [] };
      nutrition_logs: { Row: { id: number; user_id: string; food_name: string; quantity: number | null; unit: string | null; calories: number | null; protein_g: number | null; carbs_g: number | null; fat_g: number | null; meal_type: string | null; logged_at: string; notes: string | null; created_at: string }; Insert: { id?: never; user_id: string; food_name: string; quantity?: number | null; unit?: string | null; calories?: number | null; protein_g?: number | null; carbs_g?: number | null; fat_g?: number | null; meal_type?: string | null; logged_at?: string; notes?: string | null; created_at?: string }; Update: Partial<Database['public']['Tables']['nutrition_logs']['Insert']>; Relationships: [] };
      ai_conversations: { Row: { id: number; user_id: string; title: string | null; created_at: string; updated_at: string }; Insert: { id?: never; user_id: string; title?: string | null; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['ai_conversations']['Insert']>; Relationships: [] };
      ai_messages: { Row: { id: number; conversation_id: number; role: string; content: string; created_at: string }; Insert: { id?: never; conversation_id: number; role: string; content: string; created_at?: string }; Update: Partial<Database['public']['Tables']['ai_messages']['Insert']>; Relationships: [] };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: { app_role: 'client' | 'trainer'; program_status: 'draft' | 'active' | 'archived'; relationship_status: 'pending' | 'active' | 'revoked'; set_type: 'warmup' | 'working' | 'dropset' | 'failure' | 'amrap'; workout_status: 'planned' | 'in_progress' | 'completed' | 'skipped' };
    CompositeTypes: Record<string, never>;
  };
};

export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
export type TablesInsert<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert'];
export type TablesUpdate<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update'];
export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T];
